import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  X,
  Copy,
  Check,
  Download,
  BookOpen,
  ListOrdered,
  FileText,
  Smile,
  CheckSquare,
  RefreshCw,
  Zap,
} from 'lucide-react';
import { api } from '../api/client';

export const AISummaryModal = ({
  isOpen,
  note,
  onClose,
  onSummarySaved,
}) => {
  const [activeTab, setActiveTab] = useState('summary');
  const [loading, setLoading] = useState(false);
  const [aiData, setAiData] = useState(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (note && isOpen) {
      if (note.aiSummary && note.aiSummary.summary) {
        setAiData(note.aiSummary);
      } else {
        // Automatically generate if not present
        handleGenerate();
      }
    }
  }, [note, isOpen]);

  if (!isOpen || !note) return null;

  const handleGenerate = async () => {
    setLoading(true);
    setError('');
    try {
      const res = await api.summarize({
        content: note.content,
        title: note.title,
        mode: activeTab,
        noteId: note._id,
      });

      if (res.success && res.data) {
        setAiData(res.data);
        if (onSummarySaved) {
          onSummarySaved(res.data);
        }
      }
    } catch (err) {
      setError(err.message || 'Failed to generate AI summary');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    let textToCopy = '';
    if (activeTab === 'summary') {
      textToCopy = aiData?.summary || '';
    } else if (activeTab === 'keyPoints') {
      textToCopy = (aiData?.keyPoints || []).join('\n• ');
    } else if (activeTab === 'flashcards') {
      textToCopy = (aiData?.flashcards || [])
        .map((f, i) => `Q${i + 1}: ${f.question}\nA: ${f.answer}`)
        .join('\n\n');
    } else if (activeTab === 'eli5') {
      textToCopy = aiData?.eli5 || '';
    } else if (activeTab === 'actionItems') {
      textToCopy = (aiData?.actionItems || []).map((a) => `[ ] ${a}`).join('\n');
    }

    if (textToCopy) {
      navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleExport = () => {
    const studySheet = `
# AI Study Sheet: ${note.title}
Generated: ${new Date().toLocaleDateString()}

## 📌 Executive Summary
${aiData?.summary || 'N/A'}

## 🎯 Key Takeaways & Core Points
${(aiData?.keyPoints || []).map((k) => `- ${k}`).join('\n')}

## 💡 Active Recall Flashcards
${(aiData?.flashcards || []).map((f, idx) => `### Card ${idx + 1}\n**Q:** ${f.question}\n**A:** ${f.answer}\n`).join('\n')}

## 👶 ELI5 (Simplified Analogy)
${aiData?.eli5 || 'N/A'}

## ✅ Action Items & Next Steps
${(aiData?.actionItems || []).map((a) => `- [ ] ${a}`).join('\n')}

---
Generated by Notes.AI Smart Assistant
`;

    const blob = new Blob([studySheet], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${note.title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_ai_study_sheet.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabs = [
    { id: 'summary', label: 'Executive Summary', icon: FileText },
    { id: 'keyPoints', label: 'Key Points', icon: ListOrdered },
    { id: 'flashcards', label: 'Flashcards', icon: BookOpen },
    { id: 'eli5', label: 'ELI5 (Simple)', icon: Smile },
    { id: 'actionItems', label: 'Action Items', icon: CheckSquare },
  ];

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div
        className="modal-content"
        style={{ maxWidth: '860px', height: '88vh' }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div
          style={{
            padding: '20px 24px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            borderBottom: '1px solid var(--border-color)',
            background: 'linear-gradient(90deg, rgba(99, 102, 241, 0.08), rgba(236, 72, 153, 0.08))',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div
              style={{
                width: '38px',
                height: '38px',
                borderRadius: '10px',
                background: 'var(--accent-gradient)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                boxShadow: 'var(--shadow-glow)',
              }}
            >
              <Sparkles size={20} color="#ffffff" />
            </div>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <h3 style={{ fontSize: '1.2rem', fontWeight: 700 }}>AI Summarization Studio</h3>
                <span className="badge ai-pulse-badge">Smart AI</span>
              </div>
              <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                Target Note: <span style={{ color: 'var(--text-primary)', fontWeight: 600 }}>{note.title}</span>
              </p>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <button
              className="btn-secondary"
              style={{ padding: '7px 12px', fontSize: '0.82rem' }}
              onClick={handleGenerate}
              disabled={loading}
            >
              <RefreshCw size={14} className={loading ? 'spin-anim' : ''} />
              <span>{loading ? 'Analyzing...' : 'Regenerate'}</span>
            </button>
            <button
              onClick={onClose}
              style={{
                background: 'none',
                border: 'none',
                color: 'var(--text-muted)',
                cursor: 'pointer',
                padding: '4px',
              }}
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Studio Sub-bar (Word reduction metrics & Mode tabs) */}
        <div
          style={{
            padding: '12px 24px',
            background: 'var(--bg-input)',
            borderBottom: '1px solid var(--border-color)',
            display: 'flex',
            flexWrap: 'wrap',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '12px',
          }}
        >
          {/* Mode Selector Tabs */}
          <div style={{ display: 'flex', gap: '6px', overflowX: 'auto' }}>
            {tabs.map((tab) => {
              const Icon = tab.icon;
              const isSelected = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '6px',
                    padding: '7px 12px',
                    borderRadius: 'var(--radius-sm)',
                    fontSize: '0.82rem',
                    fontWeight: 600,
                    background: isSelected ? 'var(--accent-primary)' : 'transparent',
                    color: isSelected ? '#ffffff' : 'var(--text-secondary)',
                    transition: 'var(--transition)',
                    whiteSpace: 'nowrap',
                  }}
                >
                  <Icon size={14} />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>

          {/* Word Metrics Pill */}
          {aiData && (
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                fontSize: '0.78rem',
                color: 'var(--text-muted)',
              }}
            >
              <span
                style={{
                  padding: '3px 10px',
                  borderRadius: 'var(--radius-full)',
                  background: 'rgba(16, 185, 129, 0.15)',
                  color: '#34d399',
                  fontWeight: 700,
                }}
              >
                ✨ {aiData.wordReductionPercent || 0}% Reduced
              </span>
              <span>
                ({aiData.originalWordCount || 0} → {aiData.summaryWordCount || 0} words)
              </span>
            </div>
          )}
        </div>

        {/* Content Viewer Area */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '24px' }}>
          {error && (
            <div
              style={{
                padding: '14px',
                borderRadius: 'var(--radius-sm)',
                background: 'rgba(244, 63, 94, 0.12)',
                color: '#fb7185',
                border: '1px solid rgba(244, 63, 94, 0.3)',
                marginBottom: '16px',
                fontSize: '0.88rem',
              }}
            >
              {error}
            </div>
          )}

          {loading ? (
            <div
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                height: '240px',
                gap: '16px',
              }}
            >
              <div
                style={{
                  width: '48px',
                  height: '48px',
                  borderRadius: '50%',
                  border: '3px solid rgba(99, 102, 241, 0.2)',
                  borderTopColor: '#6366f1',
                  animation: 'spin 1s linear infinite',
                }}
              />
              <div style={{ textAlign: 'center' }}>
                <p style={{ fontWeight: 600, fontSize: '1rem', color: 'var(--text-primary)' }}>
                  Analyzing note semantics & compressing information...
                </p>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                  Extracting core concepts, questions, and action items
                </p>
              </div>
            </div>
          ) : aiData ? (
            <div>
              {/* Executive Summary View */}
              {activeTab === 'summary' && (
                <div className="glass-panel" style={{ padding: '24px', lineHeight: 1.7, fontSize: '0.95rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
                    <FileText size={18} color="#6366f1" />
                    <h4 style={{ fontSize: '1.05rem', fontWeight: 700 }}>Executive Synthesis</h4>
                  </div>
                  <p style={{ color: 'var(--text-primary)', whiteSpace: 'pre-line' }}>{aiData.summary}</p>
                </div>
              )}

              {/* Key Points View */}
              {activeTab === 'keyPoints' && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                  {(aiData.keyPoints || []).map((point, idx) => (
                    <div
                      key={idx}
                      className="glass-panel"
                      style={{
                        padding: '16px 20px',
                        display: 'flex',
                        alignItems: 'flex-start',
                        gap: '14px',
                        borderRadius: 'var(--radius-md)',
                      }}
                    >
                      <div
                        style={{
                          width: '26px',
                          height: '26px',
                          borderRadius: '50%',
                          background: 'rgba(99, 102, 241, 0.15)',
                          color: '#818cf8',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          fontSize: '0.8rem',
                          fontWeight: 700,
                          flexShrink: 0,
                          marginTop: '2px',
                        }}
                      >
                        {idx + 1}
                      </div>
                      <p style={{ fontSize: '0.92rem', color: 'var(--text-primary)', lineHeight: 1.5 }}>
                        {point}
                      </p>
                    </div>
                  ))}
                </div>
              )}

              {/* Flashcards View */}
              {activeTab === 'flashcards' && (
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '16px' }}>
                  {(aiData.flashcards || []).map((card, idx) => (
                    <div
                      key={idx}
                      className="glass-panel"
                      style={{
                        padding: '18px',
                        borderRadius: 'var(--radius-md)',
                        borderLeft: '4px solid #818cf8',
                      }}
                    >
                      <div style={{ fontSize: '0.72rem', fontWeight: 700, color: '#818cf8', textTransform: 'uppercase', marginBottom: '6px' }}>
                        Question {idx + 1}
                      </div>
                      <div style={{ fontWeight: 600, fontSize: '0.92rem', marginBottom: '12px', color: 'var(--text-primary)' }}>
                        {card.question}
                      </div>
                      <div style={{ fontSize: '0.72rem', fontWeight: 700, color: '#34d399', textTransform: 'uppercase', marginBottom: '4px' }}>
                        Answer
                      </div>
                      <div style={{ fontSize: '0.86rem', color: 'var(--text-secondary)', lineHeight: 1.45 }}>
                        {card.answer}
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* ELI5 View */}
              {activeTab === 'eli5' && (
                <div
                  className="glass-panel"
                  style={{
                    padding: '24px',
                    borderRadius: 'var(--radius-lg)',
                    background: 'linear-gradient(135deg, rgba(245, 158, 11, 0.1), rgba(236, 72, 153, 0.08))',
                    border: '1px solid rgba(245, 158, 11, 0.25)',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
                    <Smile size={20} color="#f59e0b" />
                    <h4 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#fbbf24' }}>
                      Explain Like I'm 5 Analogy
                    </h4>
                  </div>
                  <p style={{ color: 'var(--text-primary)', fontSize: '0.95rem', lineHeight: 1.65 }}>
                    {aiData.eli5 || 'No ELI5 summary generated yet.'}
                  </p>
                </div>
              )}

              {/* Action Items View */}
              {activeTab === 'actionItems' && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                  {(aiData.actionItems || []).map((item, idx) => (
                    <div
                      key={idx}
                      className="glass-panel"
                      style={{
                        padding: '14px 18px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '12px',
                        borderRadius: 'var(--radius-md)',
                      }}
                    >
                      <input
                        type="checkbox"
                        style={{ width: '18px', height: '18px', cursor: 'pointer', accentColor: '#6366f1' }}
                      />
                      <span style={{ fontSize: '0.9rem', color: 'var(--text-primary)' }}>{item}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          ) : (
            <div style={{ textAlign: 'center', padding: '60px 0', color: 'var(--text-muted)' }}>
              Click "Regenerate" to generate AI insights for this note.
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div
          style={{
            padding: '16px 24px',
            background: 'var(--bg-input)',
            borderTop: '1px solid var(--border-color)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
          }}
        >
          <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <Zap size={14} color="#6366f1" />
            <span>AI Model Engine: {aiData?.source || 'Gemini 1.5 Flash / Local NLP'}</span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <button className="btn-secondary" onClick={handleCopy} disabled={!aiData}>
              {copied ? <Check size={16} color="#10b981" /> : <Copy size={16} />}
              <span>{copied ? 'Copied!' : 'Copy Section'}</span>
            </button>
            <button className="btn-secondary" onClick={handleExport} disabled={!aiData}>
              <Download size={16} />
              <span>Export Study Sheet</span>
            </button>
            <button className="btn-primary" onClick={onClose}>
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
